### ISSUE TITLE
a tag won't be rendered when it has a style definition and a falsy child

### ISSUE THREAD

**Issue by keyanzhang** [flintjs/flint#111] opened 2015-11-09 03:36 UTC
![bug](https://cloud.githubusercontent.com/assets/2268452/11025371/331e75a4-8668-11e5-8cff-c8a2d859323e.gif)

code used in the gif:
``` js
view Main {
  const num = 10

  <p>the following line will disappear when the tag has a style and its child is falsy</p>
  <div>{num}</div>
  <div>this guy wont disappear: {num}</div>

  $ = {
    margin: 80,
  }

  // remove the style to see the difference
  $div = {
    color: 'blue',
  }
}
```

**Comment by natew** [comment] 2015-11-09 08:52
Woah, great find. Will check this tomorrow.

**Comment by natew** [comment] 2015-11-09 20:48
Can you try again? We've done a lot of style updates so this is working well for me without more changes: 
![image](https://cloud.githubusercontent.com/assets/12100/11046095/2bc9f332-86e0-11e5-801c-1fd9b92fe1f7.png)

**Comment by ncammarata** [comment] 2015-11-09 20:49
If all Github issues were this well done no project would be closed source

**Comment by natew** [comment] 2015-11-09 21:29
@keyanzhang Curious, how do you record your stuff?

I'd pay money for a simple app that let me record my screen have auto uploaded the html5 video / gif to my github, and gave me a link in my clipboard.

**Comment by keyanzhang** [comment] 2015-11-09 22:06
Yeah it's fixed now. Thanks! I'm very curious about how the compiler/transformer works -- would you mind if I ask which commit fixed the issue?

@natew I used [licecap](http://www.cockos.com/licecap/) here. It gets the work done but the quality isn't so great. I once tried using QuickTime and ffmpeg to [roll my own gif](http://superuser.com/a/556031/298544) and it was kinda fun.

**Comment by natew** [comment] 2015-11-09 23:32
Actually not sure what fixed it because I couldn't replicate, but check out the packages folder, transformer is our babel plugin, the hot reload stuff is mostly in runner (server), some in flint.js (client)

**Comment by keyanzhang** [comment] 2015-11-09 23:34
cool thx!

**Comment by keyanzhang** [comment] 2015-11-10 07:11
Oops, I happened to reproduce it on 1.3.83 :stuck_out_tongue:. Not exactly the same case though.  

![image](https://cloud.githubusercontent.com/assets/2268452/11056397/8200d6e8-874f-11e5-9796-6d3b95a72432.png)

``` js
view Main {
  const data = [0, 1, 2, 3, 4]

  <Square
    repeat={data}
    width={40}
  >
    {_}
  </Square>
}

view Square {
  $ = {
    width: view.props.width, // try changing me to 40, IOW referencing no props

    // the following styles have nothing to do with this issue
    display: 'inline-block',
    height: 40,
    border: '1px solid black',
  }
}
```

Again, it only happens when the child is falsy (`0`). Changing the child from `{_}` to `{_ + 'bla'}` will also solve the issue. My guess is you have a `if (!this.props.children) { ... }` somewhere.

**Comment by natew** [comment] 2015-11-10 08:30
Wondering if this is due to us being daredevils and using master branch of React...

**Comment by natew** [comment] 2015-11-10 08:39
@keyanzhang looks like from [this sketchy site](http://fixall.online/react-doesnt-render-falsy-values--be-it-a-component/5214722/) that React just doesn't render falsy values?

That does seem incredibly strange though... I guess we could intercept them but not sure how much that will take to support.

**Comment by keyanzhang** [comment] 2015-11-10 09:00
React doesn't render `null`, `false`, or `undefined`, but `0` should be fine... Could you reproduce it on your side this time?

**Comment by natew** [comment] 2015-11-10 09:17
I could reproduce, but I logged right before we pass it over to React.createElement and it passes in the value seemingly fine. Have a few other big things to focus on tonight but I'll peek back at this soon.

**Comment by natew** [comment] 2015-11-11 22:48
Ah figured it out. We are using an old version of Radium because the new versions are breaking for us. I'm going to try an upgrade to the newest, see if it works. If not, I'll just backport the patch for now and open an issue on Radium.

**Comment by keyanzhang** [comment] 2015-11-11 22:53
:+1:

**Comment by natew** [comment] 2015-11-11 23:12
Fixed in https://github.com/flintjs/flint/commit/70bab74bd63d943f2b2d2d098949038e94fde94f

**Closed by natew** 2015-11-11 23:12 UTC
