### ISSUE TITLE
Synchronous Flint.router.go() in on('props') gives an ugly crash

### ISSUE THREAD

**Issue by liron00** [flintjs/flint#139] opened 2015-11-12 19:41 UTC
on('props', () => {
        if (view.props.params.slugId == 'x') {
            Flint.router.go('y')
            return
        }
    }

![image](https://cloud.githubusercontent.com/assets/699733/11129055/319662ce-8932-11e5-8265-1115a08ecb7a.png)

If I wrap the Flint.router.go call in a setTimeout, it's fine.

**Comment by natew** [comment] 2015-11-12 19:54
Will check this out. Oh btw in the new flint you have to use `on.props`. As a heads up.

**Comment by natew** [comment] 2015-11-12 20:06
Tried reproducing, ran into a bug where it would infinite loop pretty badly. Your example seemed to work for me. Try again?

**Comment by liron00** [comment] 2015-11-12 20:38
Ok after a lot of investigation I reduced the repro step to this:

    view Main {
      on.props(() => {
        if (Flint.router.isActive('/x')) {
          Flint.router.go('/y')
        }
      })
      
      <main>
        <Foo />
      </main>
    }

    view Foo {
      <img src="/images/loader.gif" />
    }


Which does this when visiting /x:

![image](https://cloud.githubusercontent.com/assets/699733/11130504/44afc4d8-893a-11e5-9bd9-098059984912.png)

**Comment by natew** [comment] 2015-11-13 00:22
Yea, so props will run right as it mounts. Which means it's trying to redirect before it finishes mounting. `on.mount` will work in this case.

We should have better warnings or even just detect if it's pre-mount and wait for it.

**Comment by liron00** [comment] 2015-11-13 16:51
Ok I think the pattern for this situation is actually to call on.mount()
inside on.props().

--
*Liron Shapira*, Chief Science Officer
US: +1 408.621.6667 | 303 Bryant St, Mountain View, CA 94041
Israel: +972 54.457.5776 | Azrieli Round Tower Fl 29, 132 Menachem Begin
Rd, Tel Aviv, Israel 67021
<http://i.imgur.com/dpMvVRI.png>

**Comment by natew** [comment] 2015-11-13 19:28
Hm... that works I guess, though hard to understand to a beginner.

Ideally your code just "works", and we have Flint.router be smart about the mounted status. Since it is our internal router. We should at very least throw an error.

**Comment by natew** [comment] 2016-01-19 05:52
Should be fixed in 63b3364c03b48bfcbd112d97433931e37ea7d6d5 (reopen if no)

**Closed by natew** 2016-01-19 05:52 UTC
